version: "3"

services:
    db:
        image: mysql:5.7
        env_file: .docker-env
        container_name: "study-mysql5.7"
        volumes:
            - "study_mysql_db:/var/lib/mysql"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 8080:80
        env_file: .docker-env
        container_name: "study_mysql_phpmyadmin"
volumes:
    study_mysql_db:
